name: Bienvenida!

on:
  push:
    branches:
      - master

jobs:
  saludo_job:
    runs-on: ubuntu-latest
    steps:
      - name: Saludar
        run: |
          echo "Hola Github Actions!!!"

      - name: Date
        run: |
          date

      - name: Listar entorno virtual
        run: |
          ls -l
